// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inbox.sql

package postgres

import (
	"context"
	"time"
)

const saveRestaurantInboxMessage = `-- name: SaveRestaurantInboxMessage :one
INSERT INTO restaurants.inbox (id, name, subject, data, received_at) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type SaveRestaurantInboxMessageParams struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Subject    string    `json:"subject"`
	Data       []byte    `json:"data"`
	ReceivedAt time.Time `json:"received_at"`
}

func (q *Queries) SaveRestaurantInboxMessage(ctx context.Context, arg SaveRestaurantInboxMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, saveRestaurantInboxMessage,
		arg.ID,
		arg.Name,
		arg.Subject,
		arg.Data,
		arg.ReceivedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
