// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mall.sql

package postgres

import (
	"context"
)

const saveRestaurant = `-- name: SaveRestaurant :exec
INSERT INTO restaurants.restaurants (id, name) VALUES ($1, $2)
`

type SaveRestaurantParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) SaveRestaurant(ctx context.Context, arg SaveRestaurantParams) error {
	_, err := q.db.Exec(ctx, saveRestaurant, arg.ID, arg.Name)
	return err
}
