// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RestaurantsEvent struct {
	StreamID      string    `json:"stream_id"`
	StreamName    string    `json:"stream_name"`
	StreamVersion int32     `json:"stream_version"`
	EventID       string    `json:"event_id"`
	EventName     string    `json:"event_name"`
	EventData     []byte    `json:"event_data"`
	OccurredAt    time.Time `json:"occurred_at"`
}

type RestaurantsInbox struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Subject    string    `json:"subject"`
	Data       []byte    `json:"data"`
	ReceivedAt time.Time `json:"received_at"`
}

type RestaurantsOutbox struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Subject     string             `json:"subject"`
	Data        []byte             `json:"data"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type RestaurantsRestaurant struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RestaurantsSnapshot struct {
	StreamID      string    `json:"stream_id"`
	StreamName    string    `json:"stream_name"`
	StreamVersion int32     `json:"stream_version"`
	SnapshotName  string    `json:"snapshot_name"`
	SnapshotData  []byte    `json:"snapshot_data"`
	UpdatedAt     time.Time `json:"updated_at"`
}
