// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
)

type Querier interface {
	LoadEvents(ctx context.Context, arg LoadEventsParams) ([]LoadEventsRow, error)
	LoadSnapshot(ctx context.Context, arg LoadSnapshotParams) (LoadSnapshotRow, error)
	SaveEvent(ctx context.Context, arg SaveEventParams) error
	SaveSnapshot(ctx context.Context, arg SaveSnapshotParams) error
}

var _ Querier = (*Queries)(nil)
